# GPT WAS USED TO GENERATE THIS FILE
WORD_MAPPING = {
    # Acronyms (2–3 characters)
    "ai": "AI",
    "ad": "Ads",
    "ads": "Ads",
    "app": "App",
    'florida': 'Florida',
    "aws": "AWS",
    "bp": "BP (Oil)",
    "btc": "Bitcoin",
    "ceo": "CEO",
    "chk": "CHK (beer)",
    "crm": "CRM",
    "djia": "Dow Jones",
    "dia": "Dow Jones",
    "fb": "Facebook",
    "ge": "GE",
    "gm": "GM",
    "gs": "Goldman",
    "gld": "Gold",
    "iwm": "IWM (Stock)",
    "ios": "iOS",
    "ip": "IP",
    "id": "ID",
    'gold': 'Gold',
    'silver': 'Silver',
    # "low": "LOW",
    "mac": "Mac",
    "max": "Max",
    # "na": "NA",
    "ndx": "NDX",
    "pc": "PC",
    # "pot": "POT",
    "psx": "PSX (Market)",
    "qqq": "QQQ (Stock)",
    "slv": "Silver",
    "spx": "SPX (Market)",
    "spy": "SPY (Fund)",
    # "ta": "TA",
    # "try": "Try",
    "tv": "TV",
    "us": "US",
    "usd": "USD",
    "vix": "VIX (Stock)",

    # Longer words (proper nouns, names, brands)
    "alexa": "Alexa",
    "america": "America",
    "amazon": "Amazon",
    "adidas": "Adidas",
    "bezos": "Bezos",
    "bidu": "BIDU",
    "bmw": "BMW",
    "cbs": "CBS",
    "china": "China",
    "colin": "Colin",
    "covid": "COVID",
    "disneyland": "Disneyland",
    "ebay": "eBay",
    "facebook": "Facebook",
    "fang": "FANG",
    "faang": "FAANG",
    "gild": "GILD",
    "goog": "GOOG",
    "google": "Google",
    "gunn": "Gunn",
    "iphone": "iPhone",
    "james": "James",
    "kaepernick": "Kaepernick",
    "kap": "Kap",
    "lenovo": "Lenovo",
    "louisville": "Louisville",
    "mark": "Mark",
    "mcdonald": "McDonald",
    "milan": "Milan",
    "nasdaq": "Nasdaq",
    "netflix": "Netflix",
    "nickelodeon": "Nickelodeon",
    "nvidia": "Nvidia",
    "nvda": "NVDA",
    "obama": "Obama",
    "reuters": "Reuters",
    "roku": "Roku",
    "samsung": "Samsung",
    "sec": "SEC",
    "shanghai": "Shanghai",
    "snap": "Snap",
    "sony": "Sony",
    "spotify": "Spotify",
    "target": "Target",
    "trump": "Trump",
    "tslaq": "TSLAQ (anti-Tesla)",
    "twtr": "Twitter",
    "youtube": "YouTube",
    "zuck": "Zuckerberg",
    "zuckerberg": "Zuckerberg",
    "iphones": "iPhones",
    "facebook": "Facebook",  # just in case still lowercase in other files
    "google": "Google",      # same reason as above
    "youtube": "YouTube",
    "twitter": "Twitter",
    "snap": "Snap",
    "wfc": "WFC (Stock)",  # Wells Fargo ticker
    "eth": "Ethereum",  # Ethereum
    "ms": "MS",    # could be Microsoft or shorthand, but treat it uppercase
    "gop": "GOP",
    "dr": "Dr.",
    "llc": "LLC",
    "hp": "HP",
    "nbc": "NBC",
    "espn": "ESPN",
    "sap": "SAP",
    "sony": "Sony",
    "cbs": "CBS",
    "cnn": "CNN",
    "nasa": "NASA",
    "ucl": "UCL (soccer)",  # UEFA Champions League
    "ip": "IP",    # in case it’s not in the original combined dict
    "reuters": "Reuters",
    "ebay": "eBay",  # casing
    "spotify": "Spotify",
    "nasdaq": "Nasdaq",
    "xbox": "Xbox",
    "mcdonald": "McDonald",
    "honda": "Honda",
    "visa": "Visa",
    "target": "Target",
    "kavanaugh": "Kavanaugh",
    "blasey": "Blasey",
    "christine": "Christine",
    "brett": "Brett",
    "sarandon": "Sarandon",
    "nooyi": "Nooyi",
    "indra": "Indra",
    "kendall": "Kendall",
    "morris": "Morris",
    "pembroke": "Pembroke",
    "tillerson": "Tillerson",
    "jamie": "Jamie",
    "dimon": "Dimon",
    "gunn": "Gunn",
    
        "apple": "Apple",
    "microsoft": "Microsoft",
    "tesla": "Tesla",
    "meta": "Meta",
    "oracle": "Oracle",
    "intel": "Intel",
    "ibm": "IBM",
    "paypal": "PayPal",
    "mastercard": "Mastercard",
    "goldman": "Goldman",
    "coke": "Coke",
    "pepsi": "Pepsi",
    "costco": "Costco",
    "nike": "Nike",
    "netflix": "Netflix",
    "disney": "Disney",
    "warner": "Warner",
    "playstation": "PlayStation",
    "azure": "Azure",
    "spacex": "SpaceX",
    "starbucks": "Starbucks",
    "walmart": "Walmart",
    "mcd": "MCD",  # McDonald's abbreviation

    # People
    "elon": "Elon",
    "jeff": "Jeff",
    "professor": "Professor",
    "feinstein": "Feinstein",
    "julian": "Julian",
    "robert": "Robert",
    "mané": "Mané",
    "neymar": "Neymar",
    "jackson": "Jackson",
    "alex": "Alex",
    "susan": "Susan",

    # Places
    "canada": "Canada",
    "india": "India",
    "atlanta": "Atlanta",
    "paris": "Paris",
    "georgia": "Georgia",
    "kentucky": "Kentucky",
    "united": "United",
    "orlando": "Orlando",
    "oakland": "Oakland",
    "louisville": "Louisville",

    # Concepts & Ideas
    "innovation": "Innovation",
    "leadership": "Leadership",
    "security": "Security",
    "privacy": "Privacy",
    "sustainability": "Sustainability",
    "pharma": "Pharma",
    
        "democrats": "Democrats",
    "republicans": "Republicans",
    'car':'cars',
    'movie':'movies',
    'NVDA':'NVIDIA',
    'fbi': 'FBI',
    'profit': 'profits',
    'assaulted': 'assault',
    'jd': 'Jing Dong',
    'tlt': 'TLT (Treasury)',
    'mulan': 'Mulan',
    'marvel': 'Marvel',
    
    # 'made':'',
    
}
